WITH all_distinct_ids AS (
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab01_patient WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab01_patient_staging WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab02_inpatient WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab02_inpatient_staging WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab03_outpatient WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab03_outpatient_staging WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab04_oral_rx WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab04_oral_rx_staging WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab05_inj_rx WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab05_inj_rx_staging WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab06_dpc WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab06_dpc_staging WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab07_lab WHERE PATIENTNO IS NOT NULL
    UNION
    SELECT PATIENTNO AS PATIENTNO_base FROM Tab07_lab_staging WHERE PATIENTNO IS NOT NULL
)
SELECT
    base.PATIENTNO_base AS PATIENTNO,
    CASE WHEN t_Tab01_patient.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab01_patient`,
    CASE WHEN t_Tab01_patient_staging.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab01_patient_staging`,
    CASE WHEN t_Tab02_inpatient.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab02_inpatient`,
    CASE WHEN t_Tab02_inpatient_staging.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab02_inpatient_staging`,
    CASE WHEN t_Tab03_outpatient.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab03_outpatient`,
    CASE WHEN t_Tab03_outpatient_staging.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab03_outpatient_staging`,
    CASE WHEN t_Tab04_oral_rx.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab04_oral_rx`,
    CASE WHEN t_Tab04_oral_rx_staging.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab04_oral_rx_staging`,
    CASE WHEN t_Tab05_inj_rx.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab05_inj_rx`,
    CASE WHEN t_Tab05_inj_rx_staging.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab05_inj_rx_staging`,
    CASE WHEN t_Tab06_dpc.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab06_dpc`,
    CASE WHEN t_Tab06_dpc_staging.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab06_dpc_staging`,
    CASE WHEN t_Tab07_lab.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab07_lab`,
    CASE WHEN t_Tab07_lab_staging.PATIENTNO IS NOT NULL THEN 1 ELSE 0 END AS `Tab07_lab_staging`
FROM all_distinct_ids base
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab01_patient` WHERE PATIENTNO IS NOT NULL) t_Tab01_patient ON base.PATIENTNO_base = t_Tab01_patient.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab01_patient_staging` WHERE PATIENTNO IS NOT NULL) t_Tab01_patient_staging ON base.PATIENTNO_base = t_Tab01_patient_staging.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab02_inpatient` WHERE PATIENTNO IS NOT NULL) t_Tab02_inpatient ON base.PATIENTNO_base = t_Tab02_inpatient.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab02_inpatient_staging` WHERE PATIENTNO IS NOT NULL) t_Tab02_inpatient_staging ON base.PATIENTNO_base = t_Tab02_inpatient_staging.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab03_outpatient` WHERE PATIENTNO IS NOT NULL) t_Tab03_outpatient ON base.PATIENTNO_base = t_Tab03_outpatient.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab03_outpatient_staging` WHERE PATIENTNO IS NOT NULL) t_Tab03_outpatient_staging ON base.PATIENTNO_base = t_Tab03_outpatient_staging.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab04_oral_rx` WHERE PATIENTNO IS NOT NULL) t_Tab04_oral_rx ON base.PATIENTNO_base = t_Tab04_oral_rx.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab04_oral_rx_staging` WHERE PATIENTNO IS NOT NULL) t_Tab04_oral_rx_staging ON base.PATIENTNO_base = t_Tab04_oral_rx_staging.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab05_inj_rx` WHERE PATIENTNO IS NOT NULL) t_Tab05_inj_rx ON base.PATIENTNO_base = t_Tab05_inj_rx.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab05_inj_rx_staging` WHERE PATIENTNO IS NOT NULL) t_Tab05_inj_rx_staging ON base.PATIENTNO_base = t_Tab05_inj_rx_staging.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab06_dpc` WHERE PATIENTNO IS NOT NULL) t_Tab06_dpc ON base.PATIENTNO_base = t_Tab06_dpc.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab06_dpc_staging` WHERE PATIENTNO IS NOT NULL) t_Tab06_dpc_staging ON base.PATIENTNO_base = t_Tab06_dpc_staging.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab07_lab` WHERE PATIENTNO IS NOT NULL) t_Tab07_lab ON base.PATIENTNO_base = t_Tab07_lab.PATIENTNO
LEFT JOIN (SELECT DISTINCT PATIENTNO FROM `Tab07_lab_staging` WHERE PATIENTNO IS NOT NULL) t_Tab07_lab_staging ON base.PATIENTNO_base = t_Tab07_lab_staging.PATIENTNO
ORDER BY base.PATIENTNO_base;